const TILE_TYPE_STREET = 1;
const TILE_TYPE_WALL = 2;
const TILE_TYPE_STATION = 3;
const TILE_TYPE_PACKAGE = 4;
const WIDTH = 1280;
const HEIGHT = 720; 
const COLUMN_COUNT = 16;
const TILE_SIZE = WIDTH/COLUMN_COUNT;
const ROW_COUNT = HEIGHT/TILE_SIZE;
const FRAME_RATE = 30;
const NORTH_DIRECTION = 0;
const EAST_DIRECTION = 90;
const SOUTH_DIRECTION = 180;
const WEST_DIRECTION = 270;
const TRUCK_SPEED = 0.05;

const SIMPLE_TILE_SPACE = 0;
const SIMPLE_TILE_BARRIER = 1;


